[tool.isort]
force_single_line = true  # one import per line
lines_after_imports = 2  # blank spaces after import section

[tool.coverage.report]
omit = [
    "pyftpdlib/_compat.py",
    "pyftpdlib/test/*",
    "setup.py",
]
exclude_lines = [
    "except ImportError:",
    "if PY3:",
    "if __name__ == .__main__.:",
    "if hasattr(select, 'devpoll'):",
    "if hasattr(select, 'epoll'):",
    "if hasattr(select, 'kqueue'):",
    "if hasattr(select, 'kqueue'):",
    "if os.name == 'nt':",
    "pragma: no cover",
    "raise NotImplementedError('must be implemented in subclass')",
]

[tool.pylint.messages_control]
disable = [
    "broad-except",
    "consider-using-f-string",
    "fixme",
    "import-outside-toplevel",
    "inconsistent-return-statements",
    "invalid-name",
    "logging-not-lazy",
    "misplaced-bare-raise",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "no-else-continue",
    "no-else-raise",
    "no-else-return",
    "protected-access",
    "raise-missing-from",
    "redefined-builtin",
    "too-few-public-methods",
    "too-many-instance-attributes",
    "ungrouped-imports",
    "unspecified-encoding",
    "use-maxsplit-arg",
    "useless-object-inheritance",
]

[tool.rstcheck]
ignore_messages = [
    "Unexpected possible title overline or transition",
]

[tool.tomlsort]
in_place = true
no_sort_tables = true
sort_inline_arrays = true
spaces_before_inline_comment = 2
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
